/* eslint-disable max-len */
import { IUser, ITrade, IExposure } from '@/types'

import item1 from '@/assets/images/overview/item-01.png'
import item2 from '@/assets/images/overview/item-02.png'
import item3 from '@/assets/images/overview/item-03.png'

export const accountsList: IUser[] = [
  {
    _id: '646cc6af30745b98dec36d29',
    Login: 98,
    Group: 'tempor',
    Password: 'anim',
    Enable: 34,
    EnableChangePassword: 25,
    EnableReadOnly: 25,
    EnableOTP: 80,
    PasswordInvestor: 'ullamco',
    PasswordPhone: 'ut',
    Name: 'Tisha Charles',
    Country: 'Benin',
    City: 'Homeland',
    State: 'Missouri',
    ZipCode: 'aute',
    Address: '941 Lee Avenue, Elwood, Hawaii, 9039',
    LeadSource: 'cillum',
    Phone: '+1 (951) 426-3422',
    Email: 'tishacharles@oulu.com',
    Comment:
      'Aliqua laborum quis non sit laborum ex ex do dolor velit voluptate. Laboris ad laborum qui eiusmod consectetur et ut est. Ex amet nisi cillum amet eiusmod. Aliquip ipsum magna officia dolor consectetur minim. Dolor aliqua magna do do laborum ea exercitation adipisicing. Excepteur in officia laborum consectetur ullamco officia nulla consequat.\r\n',
    Id: '646cc6afa531474b9003ff8a',
    Status: 'amet',
    Regdate: 88,
    LastDate: 91,
    Leverage: 86,
    AgentAccount: 80,
    Timestamp: 62,
    LastIp: 25,
    Balance: 21,
    PrevMonthBalance: 23,
    PrevBalance: 26,
    Credit: 39,
    InterestRate: 26,
    Taxes: 35,
    PrevMonthEquity: 21,
    PrevEquity: 24,
    PublicKey:
      'Commodo laboris anim et id non non aliqua laboris dolor. Dolor aute do non elit reprehenderit sit aliquip ea occaecat incididunt et et aute. Velit non consequat eu sint irure enim eiusmod nulla esse sunt velit id eiusmod velit. Est ut et labore sit enim reprehenderit ex enim ex dolore culpa excepteur adipisicing quis. Ad nostrud quis sit tempor nisi sit mollit adipisicing eiusmod anim ut.\r\n',
    SendReports: 30,
    OTPSecret: 'eu',
    Mqid: 24,
    UserColor: 29,
    ApiData:
      'In excepteur elit deserunt sint incididunt laborum ea enim. Incididunt tempor et laboris Lorem nulla laboris non consequat tempor tempor aliqua eiusmod nostrud pariatur. Cillum et consectetur aliqua nisi. Mollit ullamco officia pariatur fugiat non eu. Esse pariatur qui fugiat cupidatat.\r\n',
  },
  {
    _id: '646cc6afb43703daf7411fea',
    Login: 33,
    Group: 'mollit',
    Password: 'proident',
    Enable: 16,
    EnableChangePassword: 89,
    EnableReadOnly: 34,
    EnableOTP: 35,
    PasswordInvestor: 'aute',
    PasswordPhone: 'Lorem',
    Name: 'Mays Pitts',
    Country: 'Cyprus',
    City: 'Holcombe',
    State: 'Nebraska',
    ZipCode: 'esse',
    Address: '834 Sapphire Street, Malott, Guam, 7249',
    LeadSource: 'eu',
    Phone: '+1 (830) 504-3087',
    Email: 'mayspitts@oulu.com',
    Comment:
      'Magna esse et incididunt cupidatat Lorem officia mollit sit est aute reprehenderit. Cillum magna est magna ut cillum cillum eiusmod officia dolore. Ipsum labore mollit ullamco qui proident consequat duis proident cupidatat.\r\n',
    Id: '646cc6afb7360c5805ec078f',
    Status: 'quis',
    Regdate: 47,
    LastDate: 28,
    Leverage: 100,
    AgentAccount: 71,
    Timestamp: 99,
    LastIp: 23,
    Balance: 28,
    PrevMonthBalance: 28,
    PrevBalance: 35,
    Credit: 26,
    InterestRate: 32,
    Taxes: 38,
    PrevMonthEquity: 35,
    PrevEquity: 20,
    PublicKey:
      'Officia voluptate nulla veniam ad. Exercitation commodo ad duis officia esse dolore occaecat deserunt velit et et proident consectetur consequat. Nisi voluptate pariatur labore pariatur eiusmod cupidatat. Consectetur minim amet quis ut nisi non fugiat sit. Cupidatat ad veniam consequat enim est. Occaecat reprehenderit mollit sit qui do voluptate nisi cupidatat minim. Eu amet dolore ad et magna.\r\n',
    SendReports: 31,
    OTPSecret: 'aliquip',
    Mqid: 30,
    UserColor: 27,
    ApiData:
      'Nostrud ipsum aute culpa cupidatat ea eiusmod aliquip ea eu. Esse anim ipsum exercitation Lorem laborum esse dolore. Laboris est pariatur excepteur sunt non exercitation enim culpa esse ut eu commodo in anim. Sint ullamco consectetur ut magna anim deserunt deserunt quis ex.\r\n',
  },
  {
    _id: '646cc6afc8b8872f464ce004',
    Login: 16,
    Group: 'consectetur',
    Password: 'do',
    Enable: 38,
    EnableChangePassword: 65,
    EnableReadOnly: 86,
    EnableOTP: 97,
    PasswordInvestor: 'laborum',
    PasswordPhone: 'tempor',
    Name: 'Karyn Peterson',
    Country: 'Senegal',
    City: 'Glasgow',
    State: 'Nevada',
    ZipCode: 'nisi',
    Address: '197 Sutter Avenue, Belva, Michigan, 4428',
    LeadSource: 'est',
    Phone: '+1 (919) 459-2603',
    Email: 'karynpeterson@oulu.com',
    Comment:
      'Est magna velit cupidatat voluptate aliqua eiusmod tempor cillum velit mollit esse sunt. Sit ad et ea id id aute adipisicing cupidatat amet. Lorem deserunt id excepteur esse in dolore veniam occaecat velit do ad id anim.\r\n',
    Id: '646cc6af7c207f6bd186ba73',
    Status: 'officia',
    Regdate: 28,
    LastDate: 37,
    Leverage: 22,
    AgentAccount: 34,
    Timestamp: 57,
    LastIp: 23,
    Balance: 33,
    PrevMonthBalance: 20,
    PrevBalance: 32,
    Credit: 29,
    InterestRate: 38,
    Taxes: 39,
    PrevMonthEquity: 22,
    PrevEquity: 37,
    PublicKey:
      'Voluptate anim aliqua aute cupidatat aliquip pariatur. Nisi amet ipsum quis ipsum laborum ullamco cupidatat ad sint magna anim tempor cupidatat. Exercitation ad qui elit veniam velit aliqua labore nostrud ullamco aliqua esse magna cupidatat. Anim aliqua eu culpa et ex exercitation eiusmod veniam consectetur pariatur eu exercitation.\r\n',
    SendReports: 23,
    OTPSecret: 'deserunt',
    Mqid: 23,
    UserColor: 34,
    ApiData:
      'Nostrud irure ipsum sit ex anim esse adipisicing ut quis cupidatat. Culpa eu magna in nostrud consectetur in anim non cupidatat nulla reprehenderit sunt officia. Ut officia fugiat exercitation laborum qui enim tempor magna est duis aliquip. Reprehenderit enim ullamco aliquip excepteur pariatur quis.\r\n',
  },
  {
    _id: '646cc6af356411de08d56d07',
    Login: 25,
    Group: 'et',
    Password: 'non',
    Enable: 73,
    EnableChangePassword: 48,
    EnableReadOnly: 56,
    EnableOTP: 73,
    PasswordInvestor: 'officia',
    PasswordPhone: 'ea',
    Name: 'Kasey Rowland',
    Country: 'Samoa',
    City: 'Fannett',
    State: 'Alaska',
    ZipCode: 'sint',
    Address: '672 Eldert Lane, Farmington, Louisiana, 4379',
    LeadSource: 'officia',
    Phone: '+1 (858) 574-2357',
    Email: 'kaseyrowland@oulu.com',
    Comment:
      'Nisi pariatur qui ea incididunt ea magna exercitation mollit cupidatat nisi. Duis exercitation irure cupidatat non sint amet velit qui consequat adipisicing enim veniam ullamco. Do ad consectetur laboris voluptate labore sunt anim do culpa aliqua mollit occaecat dolore labore. Amet ut officia tempor dolor excepteur. Minim proident velit amet elit esse mollit proident officia pariatur quis do magna dolor est. Ullamco magna non voluptate irure non ullamco culpa dolor sit velit occaecat occaecat est. Eiusmod minim est officia sit nisi minim eiusmod minim.\r\n',
    Id: '646cc6afcf78bfe022dfd088',
    Status: 'magna',
    Regdate: 14,
    LastDate: 78,
    Leverage: 24,
    AgentAccount: 43,
    Timestamp: 22,
    LastIp: 37,
    Balance: 35,
    PrevMonthBalance: 25,
    PrevBalance: 29,
    Credit: 32,
    InterestRate: 32,
    Taxes: 29,
    PrevMonthEquity: 25,
    PrevEquity: 39,
    PublicKey:
      'Exercitation eiusmod et id minim amet in irure Lorem eiusmod dolore consectetur non dolor consectetur. Non laborum reprehenderit enim id. Occaecat non incididunt irure ullamco in.\r\n',
    SendReports: 26,
    OTPSecret: 'cupidatat',
    Mqid: 24,
    UserColor: 31,
    ApiData:
      'Pariatur ullamco est voluptate aute minim culpa ex non labore amet cillum officia voluptate. Duis mollit ipsum ex tempor adipisicing. Consequat ipsum commodo irure ex elit ad est enim aute cupidatat in. Cupidatat duis laboris voluptate veniam nisi Lorem voluptate labore minim. Esse quis voluptate fugiat eiusmod ullamco minim. Dolor velit culpa mollit nostrud ex non cillum magna cillum officia deserunt est enim.\r\n',
  },
  {
    _id: '646cc6aff90c45bfedfa3e55',
    Login: 85,
    Group: 'sint',
    Password: 'adipisicing',
    Enable: 38,
    EnableChangePassword: 44,
    EnableReadOnly: 56,
    EnableOTP: 20,
    PasswordInvestor: 'consectetur',
    PasswordPhone: 'ex',
    Name: 'Cooper Castaneda',
    Country: 'S. Georgia and S. Sandwich Isls.',
    City: 'Falmouth',
    State: 'New Mexico',
    ZipCode: 'sit',
    Address: '427 Burnett Street, Boonville, New Jersey, 8007',
    LeadSource: 'irure',
    Phone: '+1 (959) 538-2844',
    Email: 'coopercastaneda@oulu.com',
    Comment:
      'Eu elit Lorem quis veniam proident qui quis quis ad eiusmod aliqua velit. Laborum duis magna excepteur laboris sunt amet quis irure occaecat velit ipsum labore. Ad esse fugiat duis occaecat sint incididunt exercitation nostrud aliqua.\r\n',
    Id: '646cc6afa37e4bdc6f54eb8f',
    Status: 'qui',
    Regdate: 31,
    LastDate: 15,
    Leverage: 41,
    AgentAccount: 83,
    Timestamp: 38,
    LastIp: 36,
    Balance: 40,
    PrevMonthBalance: 38,
    PrevBalance: 34,
    Credit: 23,
    InterestRate: 33,
    Taxes: 29,
    PrevMonthEquity: 38,
    PrevEquity: 26,
    PublicKey:
      'Lorem consequat pariatur consectetur ullamco minim aliqua ipsum ut anim magna dolor. Do veniam magna aute ea. Officia sit non irure eu ex ut commodo dolor duis mollit. Exercitation duis exercitation adipisicing fugiat nisi anim eu irure veniam. Adipisicing Lorem ullamco mollit consequat tempor excepteur. Reprehenderit sit excepteur magna irure sunt tempor eiusmod occaecat ut velit magna ut deserunt. Tempor mollit cillum non laboris cillum ea labore.\r\n',
    SendReports: 25,
    OTPSecret: 'voluptate',
    Mqid: 30,
    UserColor: 37,
    ApiData:
      'Minim deserunt ullamco amet culpa deserunt enim sint. Occaecat do in irure adipisicing exercitation ullamco dolore eiusmod est occaecat ex magna. Enim proident nulla sunt fugiat laboris incididunt consequat labore aute nisi tempor pariatur culpa.\r\n',
  },
  {
    _id: '646cc6af2cfa3959b219d051',
    Login: 78,
    Group: 'occaecat',
    Password: 'ullamco',
    Enable: 35,
    EnableChangePassword: 29,
    EnableReadOnly: 40,
    EnableOTP: 77,
    PasswordInvestor: 'dolor',
    PasswordPhone: 'quis',
    Name: 'Barber Lara',
    Country: 'Cook Islands',
    City: 'Barrelville',
    State: 'North Dakota',
    ZipCode: 'esse',
    Address: '666 Aurelia Court, Singer, Kentucky, 1933',
    LeadSource: 'adipisicing',
    Phone: '+1 (958) 485-2499',
    Email: 'barberlara@oulu.com',
    Comment:
      'Ex ea commodo dolore ea anim do cillum ut. Sit consectetur laboris occaecat cupidatat exercitation sunt ullamco elit ut. Elit est id voluptate aliquip eiusmod cillum aliquip dolore.\r\n',
    Id: '646cc6af19c50a2664dc206a',
    Status: 'quis',
    Regdate: 61,
    LastDate: 45,
    Leverage: 51,
    AgentAccount: 39,
    Timestamp: 78,
    LastIp: 26,
    Balance: 34,
    PrevMonthBalance: 28,
    PrevBalance: 38,
    Credit: 33,
    InterestRate: 28,
    Taxes: 20,
    PrevMonthEquity: 22,
    PrevEquity: 40,
    PublicKey:
      'Proident irure mollit esse pariatur. Enim cupidatat dolor laborum labore aute magna amet laboris irure ipsum. Nulla tempor fugiat esse ad irure aliqua et ipsum elit veniam ea ipsum consequat ea. Exercitation mollit id aute et. Incididunt incididunt ut do ex adipisicing qui labore ea sunt qui eiusmod. Laborum eiusmod Lorem pariatur veniam deserunt consequat elit excepteur in adipisicing commodo officia.\r\n',
    SendReports: 24,
    OTPSecret: 'culpa',
    Mqid: 24,
    UserColor: 27,
    ApiData:
      'Id cupidatat eiusmod cupidatat pariatur sint non et sint culpa exercitation exercitation pariatur reprehenderit dolor. Tempor adipisicing quis quis nulla eu tempor nulla sunt exercitation Lorem duis. Amet occaecat occaecat tempor amet consequat tempor veniam tempor ad do aliqua voluptate do. Do fugiat exercitation ullamco excepteur cillum tempor. Officia amet consequat non irure consequat sint consectetur occaecat labore exercitation in duis non culpa.\r\n',
  },
]

export const tradesData: ITrade[] = [
  {
    Timestamp: 65,
    Type: 'buy',
    Login: 10,
    Digits: 70,
    Cmd: 93,
    Activation: 46,
    Volume: 29,
    OpenTime: 47,
    State: 25,
    OpenPrice: 33,
    Sl: 32,
    Tp: 58,
    Commission: 97,
    CloseTime: 47,
    Expiration: 35,
    ClosePrice: 87,
    Profit: 75,
    GwVolume: 89,
    Reason: 34,
    ConvRates: [36, 24, 47, 90, 81, 19, 43],
    CommissionAgent: 30,
    Storage: 39,
    Order: 79,
    Taxes: 71,
    Magic: 25,
    Comment: 'labore',
    GwOrder: 49,
    Symbol: 'deserunt',
    GwOpenPrice: 23,
    GwClosePrice: 89,
    MarginRate: 36,
    ApiData: [50, 76, 44, 55, 44, 92],
    NewTradingEngine: true,
  },
  {
    Timestamp: 82,
    Type: 'buy',
    Login: 52,
    Digits: 64,
    Cmd: 64,
    Activation: 69,
    Volume: 65,
    OpenTime: 82,
    State: 86,
    OpenPrice: 70,
    Sl: 24,
    Tp: 92,
    Commission: 89,
    CloseTime: 22,
    Expiration: 34,
    ClosePrice: 10,
    Profit: 92,
    GwVolume: 23,
    Reason: 38,
    ConvRates: [42, 16, 93, 59, 24],
    CommissionAgent: 30,
    Storage: 45,
    Order: 35,
    Taxes: 62,
    Magic: 14,
    Comment: 'in',
    GwOrder: 80,
    Symbol: 'ipsum',
    GwOpenPrice: 85,
    GwClosePrice: 99,
    MarginRate: 79,
    ApiData: [68, 90, 89, 57, 77, 37],
    NewTradingEngine: false,
  },
  {
    Timestamp: 49,
    Type: 'sell',
    Login: 17,
    Digits: 76,
    Cmd: 58,
    Activation: 48,
    Volume: 23,
    OpenTime: 47,
    State: 40,
    OpenPrice: 35,
    Sl: 25,
    Tp: 73,
    Commission: 53,
    CloseTime: 94,
    Expiration: 47,
    ClosePrice: 36,
    Profit: 40,
    GwVolume: 16,
    Reason: 55,
    ConvRates: [27, 52, 25, 83, 31, 69],
    CommissionAgent: 85,
    Storage: 74,
    Order: 65,
    Taxes: 59,
    Magic: 65,
    Comment: 'minim',
    GwOrder: 78,
    Symbol: 'in',
    GwOpenPrice: 33,
    GwClosePrice: 16,
    MarginRate: 57,
    ApiData: [12, 51, 44, 95, 81, 55],
    NewTradingEngine: true,
  },
  {
    Timestamp: 98,
    Type: 'buy',
    Login: 18,
    Digits: 89,
    Cmd: 98,
    Activation: 41,
    Volume: 62,
    OpenTime: 46,
    State: 79,
    OpenPrice: 93,
    Sl: 80,
    Tp: 14,
    Commission: 69,
    CloseTime: 62,
    Expiration: 82,
    ClosePrice: 71,
    Profit: 51,
    GwVolume: 55,
    Reason: 76,
    ConvRates: [98, 73, 19, 42, 61, 32],
    CommissionAgent: 39,
    Storage: 57,
    Order: 72,
    Taxes: 73,
    Magic: 17,
    Comment: 'duis',
    GwOrder: 92,
    Symbol: 'est',
    GwOpenPrice: 19,
    GwClosePrice: 98,
    MarginRate: 19,
    ApiData: [88, 50, 43, 43, 93, 54],
    NewTradingEngine: false,
  },
  {
    Timestamp: 64,
    Type: 'sell',
    Login: 36,
    Digits: 38,
    Cmd: 63,
    Activation: 15,
    Volume: 70,
    OpenTime: 41,
    State: 14,
    OpenPrice: 73,
    Sl: 38,
    Tp: 36,
    Commission: 59,
    CloseTime: 65,
    Expiration: 67,
    ClosePrice: 68,
    Profit: 24,
    GwVolume: 69,
    Reason: 20,
    ConvRates: [60, 49, 95, 96, 69, 53, 35],
    CommissionAgent: 62,
    Storage: 68,
    Order: 93,
    Taxes: 35,
    Magic: 31,
    Comment: 'nostrud',
    GwOrder: 43,
    Symbol: 'id',
    GwOpenPrice: 92,
    GwClosePrice: 26,
    MarginRate: 73,
    ApiData: [51, 51, 91, 87, 80, 11, 89],
    NewTradingEngine: true,
  },
]

export const exposureData: IExposure[] = [
  {
    symbolIcon: item1,
    symbol: 'AAPL.OQ',
    volume: 50,
    rate: 145.02,
    graph: 15,
  },
  {
    symbolIcon: item2,
    symbol: 'TSLA.OQ',
    volume: 3,
    rate: 202.98,
    graph: 35,
  },
  {
    symbolIcon: item3,
    symbol: 'UST',
    volume: 3999394298,
    rate: 1,
    graph: 50,
  },
]
