export interface IUser {
  _id?: string
  Login?: number
  Group?: string
  Password: string
  Enable?: number
  EnableChangePassword?: number
  EnableReadOnly?: number
  EnableOTP?: number
  PasswordInvestor?: string
  PasswordPhone?: string
  Name?: string
  Country?: string
  City?: string
  State?: string
  ZipCode?: string
  Address?: string
  LeadSource?: string
  Phone?: string
  Email?: string
  Comment?: string
  Id?: string
  Status?: string
  Regdate?: number
  LastDate?: number
  Leverage?: number
  AgentAccount?: number
  Timestamp?: number
  LastIp?: number
  Balance?: number
  PrevMonthBalance?: number
  PrevBalance?: number
  Credit?: number
  InterestRate?: number
  Taxes?: number
  PrevMonthEquity?: number
  PrevEquity?: number
  PublicKey?: string
  SendReports?: number
  OTPSecret?: string
  Mqid?: number
  UserColor?: number
  ApiData?: string
}
